### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by mbchoa** [mbchoa/presence#1]
- [ ] Write Unit Tests
- [ ] Port server bundling to Webpack
- [ ] Setup deployment pipeline
